//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Texture.rc
//
#define IDS_TEXTURENAME                 1
#define IDS_PROPERTYTAB1                2
#define IDS_AMPLITUDE                   3
#define IDS_RED                         4
#define IDS_GREEN                       5
#define IDS_BLUE                        6
#define IDS_NOISE                       7
#define IDS_COLOURS                     8
#define IDS_BLEND                       9
#define IDS_POSITION                    10
#define IDS_SKY                         11
#define IDS_SUN                         12
#define IDS_CLOUD                       13
#define IDS_BCOLOR                      14
#define IDS_HAZE                        15
#define IDS_HEIGHT                      16
#define IDS_OCTAVES                     17
#define IDS_SINTENSITY                  18
#define IDS_COVER                       19
#define IDS_SHADE                       20
#define IDS_HCOLOR                      21
#define IDS_OFFSET                      22
#define IDS_SCALE                       23
#define IDS_TRANSPARENCY                24
#define IDS_SI                          25
#define IDS_TYPE                        26
#define IDS_CLASSIC                     27
#define IDS_CIRRUS                      28
#define IDS_FLUFFY                      29
#define IDS_OREN_NAYAR                  30
#define IDS_SWIRL                       31
#define IDS_PUFFY                       32
#define IDS_SUNCOLOR                    33
#define IDS_C1COLOR                     34
#define IDS_C2COLOR                     35
#define IDS_HAZECOLOR                   36
#define IDI_TEXTURE                     129
#define IDD_ATTRIBUTES_PAGE             244
#define IDD_SKY_PAGE                    244
#define IDD_NOISE_PAGE                  245
#define IDD_COLOUR_PAGE                 246
#define IDD_CLOUD_PAGE                  246
#define IDD_BLEND_DIALOG                247
#define IDD_SUN_DIALOG                  247
#define IDD_POSITION_PAGE               248
#define IDC_MYCOLOR                     13000
#define IDC_AMPLITUDE                   13001
#define IDC_HAZE                        13001
#define IDC_AMPLITUDE_SPIN              13002
#define IDC_HAZE_SPIN                   13002
#define IDC_AMPLITUDE_SLIDER            13003
#define IDC_NOISE_AMT                   13004
#define IDC_NOISE_AMT_SPIN              13005
#define IDC_NOISE_FREQ                  13006
#define IDC_NOISE_FREQ_SPIN             13007
#define IDC_BACK_COLOUR                 13008
#define IDC_CLOUD_COLOUR                13008
#define IDC_FORE_COLOUR                 13009
#define IDC_CLOUDS_COLOUR               13009
#define IDC_BACK_REFLECT                13010
#define IDC_BACK_REFLECT_SPIN           13011
#define IDC_BACK_TRANSPARENT            13012
#define IDC_BACK_TRANSPARENT_SPIN       13013
#define IDC_FORE_REFLECT                13014
#define IDC_HEIGHT                      13014
#define IDC_FORE_REFLECT_SPIN           13015
#define IDC_HEIGHT_SPIN                 13015
#define IDC_FORE_TRANSPARENT            13016
#define IDC_SHADE                       13016
#define IDC_FORE_TRANSPARENT_SPIN       13017
#define IDC_SHADE_SPIN                  13017
#define IDC_USE_CURRENT                 13018
#define IDC_BUMP_AMT                    13020
#define IDC_BUMP_SPIN                   13021
#define IDC_BLEND_AMT                   13022
#define IDC_BLEND_SPIN                  13023
#define IDC_OFF_X                       13024
#define IDC_OFF_X_SPIN                  13025
#define IDC_OFF_Y                       13026
#define IDC_OFF_Y_SPIN                  13027
#define IDC_OFF_Z                       13028
#define IDC_OFF_Z_SPIN                  13029
#define IDC_SCALE_X                     13030
#define IDC_SCALE_X_SPIN                13031
#define IDC_SCALE_Y                     13032
#define IDC_SCALE_Y_SPIN                13033
#define IDC_SCALE_Z                     13034
#define IDC_SCALE_Z_SPIN                13035
#define IDC_SKY_COLOUR                  13036
#define IDC_HAZE_COLOUR                 13037
#define IDC_SUN_COLOUR                  13038
#define IDC_SUNX                        13039
#define IDC_SUNX_SPIN                   13040
#define IDC_SUNY                        13041
#define IDC_SUNY_SPIN                   13042
#define IDC_SUNZ                        13043
#define IDC_SUNZ_SPIN                   13044
#define IDC_COVER                       13045
#define IDC_COVER_SPIN                  13046
#define IDC_OCTAVES                     13047
#define IDC_OCTAVES_SPIN                13048
#define IDC_TRANS                       13051
#define IDC_SUN_INTENSITY               13052
#define IDC_SUN_INTENSITY_SPIN          13053
#define IDC_ILLUM                       13054
#define IDC_TYPE                        13057

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        250
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         13058
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
