site_name: Animation:Master SDK
site_url: https://openanimationlibrary.github.io/amsdk
repo_url: https://github.com/OpenAnimationLibrary/amsdk
repo_name: OpenAnimationLibrary/amsdk
edit_uri: edit/main/docs/
strict: false

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - tables
  - attr_list
  - def_list
  - footnotes

# We'll insert a generated nav here in a moment.
# nav:
#   - Home: index.md
