//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Texture.rc
//
#define IDS_TEXTURENAME                 1
#define IDS_PROPERTYTAB1                2
#define IDS_AMPLITUDE                   3
#define IDS_RED                         4
#define IDS_GREEN                       5
#define IDS_BLUE                        6
#define IDS_NOISE                       7
#define IDS_COLOURS                     8
#define IDS_BLEND                       9
#define IDS_POSITION                    10
#define IDS_WASH                        11
#define IDS_DARK1                       12
#define IDS_DARK2                       13
#define IDS_LIGHT                       14
#define IDS_PAPERCOLOR                  15
#define IDS_PENCILCOLOR                 16
#define IDS_PENCILNOISE                 17
#define IDS_PENCILFREQ                  18
#define IDS_WASHCOLOR                   19
#define IDS_WASHNOISE                   20
#define IDS_WASHFREQ                    21
#define IDS_PENCILSIZE                  22
#define IDS_WASHSIZE                    23
#define IDS_DARK1COLOR                  24
#define IDS_DARK2COLOR                  25
#define IDS_DARK1NOISE                  26
#define IDS_DARK2NOISE                  27
#define IDS_DARK1FREQ                   28
#define IDS_DARK2FREQ                   29
#define IDS_DARK1SIZE                   30
#define IDS_DARK2SIZE                   31
#define IDS_MIX                         33
#define IDS_FREQ                        34
#define IDS_BITMAP                      35
#define IDI_TEXTURE                     129
#define IDD_ATTRIBUTES_PAGE             244
#define IDD_NOISE_PAGE                  245
#define IDD_COLOUR_PAGE                 246
#define IDD_BLEND_DIALOG                247
#define IDD_POSITION_PAGE               248
#define IDD_WASH_PANEL                  249
#define IDD_DARK1_PANEL                 250
#define IDD_DARK2_PANEL                 251
#define IDD_LIGHT_PANEL                 252
#define IDC_MYCOLOR                     13000
#define IDC_AMPLITUDE                   13001
#define IDC_AMPLITUDE_SPIN              13002
#define IDC_AMPLITUDE_SLIDER            13003
#define IDC_NOISE_AMT                   13004
#define IDC_NOISE_AMT_SPIN              13005
#define IDC_NOISE_FREQ                  13006
#define IDC_NOISE_FREQ_SPIN             13007
#define IDC_BACK_COLOUR                 13008
#define IDC_FORE_COLOUR                 13009
#define IDC_BACK_REFLECT                13010
#define IDC_BACK_REFLECT_SPIN           13011
#define IDC_BACK_TRANSPARENT            13012
#define IDC_BACK_TRANSPARENT_SPIN       13013
#define IDC_FORE_REFLECT                13014
#define IDC_FORE_REFLECT_SPIN           13015
#define IDC_FORE_TRANSPARENT            13016
#define IDC_FORE_TRANSPARENT_SPIN       13017
#define IDC_USE_CURRENT                 13018
#define IDC_BUMP_AMT                    13020
#define IDC_BUMP_SPIN                   13021
#define IDC_BLEND_AMT                   13022
#define IDC_BLEND_SPIN                  13023
#define IDC_OFF_X                       13024
#define IDC_OFF_X_SPIN                  13025
#define IDC_OFF_Y                       13026
#define IDC_OFF_Y_SPIN                  13027
#define IDC_OFF_Z                       13028
#define IDC_OFF_Z_SPIN                  13029
#define IDC_SCALE_X                     13030
#define IDC_SCALE_X_SPIN                13031
#define IDC_SCALE_Y                     13032
#define IDC_SCALE_Y_SPIN                13033
#define IDC_SCALE_Z                     13034
#define IDC_SCALE_Z_SPIN                13035
#define IDC_NOISE                       13036
#define IDC_NOISE_SPIN                  13037
#define IDC_FREQ                        13038
#define IDC_FREQ_SPIN                   13039
#define IDC_WASH_COLOUR                 13040
#define IDC_WASH                        13041
#define IDC_WASH_SPIN                   13042
#define IDC_WASH_NOISE                  13043
#define IDC_WASH_NOISE_SPIN             13044
#define IDC_WASH_FREQ_SPIN              13045
#define IDC_WASH_FREQ                   13046
#define IDC_DARK1_COLOUR                13047
#define IDC_DARK1                       13048
#define IDC_DARK1_NOISE                 13049
#define IDC_DARK1_FREQ                  13050
#define IDC_DARK1_NOISE_SPIN            13051
#define IDC_DARK1_FREQ_SPIN             13052
#define IDC_DARK2_COLOUR                13053
#define IDC_DARK2                       13054
#define IDC_DARK2_SPIN                  13055
#define IDC_DARK1_SPIN                  13056
#define IDC_LIGHTX                      13061
#define IDC_LIGHTX_SPIN                 13062
#define IDC_LIGHTY                      13063
#define IDC_LIGHTY_SPIN                 13064
#define IDC_LIGHTZ                      13065
#define IDC_LIGHTZ_SPIN                 13066
#define IDC_DARK2_NOISE_SPIN            13067
#define IDC_DARK2_NOISE                 13068
#define IDC_DARK2_FREQ                  13069
#define IDC_DARK2_FREQ_SPIN             13070
#define IDC_PAPER_FREQ                  13071
#define IDC_PAPER_FREQ_SPIN             13072
#define IDC_PAPER_COLOUR                13074
#define IDC_PVAR                        13075
#define IDC_PVAR_SPIN                   13076
#define IDC_TEXTURE_NAME                13077
#define IDC_TEXTURE_BUT                 13078

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        253
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         13079
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
